Add feature redundant master api
vshn/signalilo pull request #114
Opened 2022-09-15 12:49 UTC by pdorschner

This PR fixes '[Feature Request] Support for Redundant Master API's' #57 

It' now possible to specify one or more Icinga-URLs. If one URL is not reachable, it'll switch to the URL which doesn't response with an error.
## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Update the README.
- [ ] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [x] Link this PR to related issues.

2022-09-19 14:03 UTC, simu commented
Hi, thanks for the contribution, I'll have a look soon

2022-09-30 08:03 UTC, pdorschner commented
Hi,
thank you for your reply. I added a bunch of changes, e.G. Readme-Update, Dockerfile, etc.
More over, the changes/PR has been tested and it worked as expected. So can I help you with something to make this PR get merged?

Best regards

2022-09-30 08:10 UTC, pdorschner commented
The Build fails because there are missing methods in the go-icinga2-client, see https://github.com/vshn/go-icinga2-client/pull/9

2022-09-30 09:48 UTC, simu requested changes
Hi,

I had a closer look (also at the go-icinga2-client PR, see my review there) and found some things that I'd like to have cleaned up before going ahead and merging this PR (after the client library PR).

Overall, the implementation as it is currently does quite a bit of unnecessary work (as pointed out in inline comments).

Additionally, please keep the README.md formatted with one sentence per line (especially the parts where you didn't make any changes) as this makes reviewing changes much easier than wrapped paragraphs.

2022-09-30 09:48 UTC, simu commented on serve.go
> +				time.Sleep(5 * time.Second)
having a hard-coded 5 second sleep in a loop with an unknown (configurable at runtime) interval seems risky, although 5 seconds is probably low enough that we'll never run into issues with missing heartbeat updates, as running the heartbeat on an interval < 30 seconds probably doesn't make a lot of sense for most setups.

2022-09-30 09:48 UTC, simu commented on config/config.go
> +	c.IcingaConfig.URL = tmp
This is strictly speaking not necessary, as you can provide repeatable arguments in environment variables separated by newlines.

If we really want to keep this, the logic should go into `ConfigInitialize()` as we only need to do this once after Signalilo starts (side-note: `newIcingaClient()` is only called once as well, but logically, it doesn't make sense that `newIcingaClient()` modifies the configuration object).

2022-09-30 09:48 UTC, simu commented on config/config.go
>  	return client, nil
We need to make sure that we have a working client before returning here. Something like

```suggestion
	for _, url := range c.IcingaConfig.URL {
		client, err = icinga2.New(icinga2.WebClient{
			URL:               url,
			Username:          c.IcingaConfig.User,
			Password:          c.IcingaConfig.Password,
			Debug:             c.IcingaConfig.Debug,
			DisableKeepAlives: c.IcingaConfig.DisableKeepAlives,
			TLSConfig:         tlsConfig})
		if err != nil {
			return nil, err
		}

		if err = client.TestIcingaApi(url); err != nil {
			// clear client if the API url wasn't reachable
			client = nil
			continue
		} else {
			break
		}
	}
	if client == nil {
		return nil, fmt.Errorf("No valid Icinga API URL found")
	}
	return client, nil
```

2022-09-30 09:48 UTC, simu commented on config/config.go
> +			TLSConfig:         tlsConfig})
We don't really need to create a fresh client to test each URL. Calling `SetIcingaUrl()` for the first URL which passes `TestIcingaApi()` would suffice. 

Something like

```
client, err := icinga2.New(icinga2.WebClient{
	URL:               c.IcingaConfig.URL,
	Username:          c.IcingaConfig.User,
	Password:          c.IcingaConfig.Password,
	Debug:             c.IcingaConfig.Debug,
	DisableKeepAlives: c.IcingaConfig.DisableKeepAlives,
	TLSConfig:         tlsConfig})
if err != nil {
	// Failed to initialize the Icinga web client, return error
	return nil, err
}
for _, url := range c.IcingaConfig.URL {
	if err = client.TestIcingaApi(url); err == nil {
		client.SetIcingaUrl(url)
		break
	}
}
if err != nil {
	// We didn't find a valid API URL, return error
	return nil, fmt.Errorf("No valid Icinga API URL found")
}
return client, nil
```

2022-10-10 12:50 UTC, pdorschner commented on README.md
> +  Parameter is used as ENV, the URLs will be splittet via comma e.G.: `"http://example.com:5665,http://example2.com:5665"`.
That's true, but in my special case, I can't specify multiple URLs with `\n` in my config. Personally

2022-10-13 11:02 UTC, pdorschner commented on README.md
> +  Parameter is used as ENV, the URLs will be splittet via comma e.G.: `"http://example.com:5665,http://example2.com:5665"`.
> Author

Nevermind, it should be implemented as you said with `\n`

2022-10-17 07:42 UTC, simu commented
Can you please update go-icinga2-client to v0.0.16 in this PR? Also, from what I can see, this PR isn't updated yet to use the final variant of the new API methods introduced in https://github.com/vshn/go-icinga2-client/pull/9.

2022-10-18 17:59 UTC, pdorschner commented
Hi,
sorry for these inconveniences... now it should be fine

2022-10-19 07:46 UTC, simu approved these changes

2022-10-19 07:48 UTC, merged